### PR TITLE
Provided admin friendly config.

### PR DESCRIPTION
**Pull request by JFoxUK**
Provide configurable options for a Salesforce Admin to decide without the need for a Salesforce Developer. This is configured through the Experience Cloud or App Builder UI.

### CODE REVIEW

**Comment by shawnchin** [comment]
Thank you. This looks extremely useful 👍🏽 .

However considering this particular project is meant to be a quick and simple demo for those starting out with initial integration, I fear it might over-complicate the codebase.

What do you think about a separate repo where we can collate your contributions, so others that have a similar use case to yours can graduate to once they've got the basic demo working?

**Comment by JFoxUK** [comment]
Screenshot 2024-07-15 at 21 23 35

Just so you can see what that additional code does - it means that a Salesforce developer isn't required for anyone who wants to use this component. It means that it can be down without code deploys to change the values, for example of the colour, rather than them being hard coded (Salesforce best practice). :) 

However, happy to follow your lead! It's your repo! Just happy to contribute and share + help wherever I can :D

**Comment by shawnchin** [comment]
I'll be frank 😏, I made this repo intentionally spare feature-wise because I never intended this to be a plug-and-play salesforce component ready for prod usage. It was always intended to be a developer resource on how one might embed the Qwil API within their system/framework (with Salesforce being the first of many to come).

That's not to say that we wouldn't be super excited if someone more qualified started a project that provides a proper Salesforce Component that's ready for prime time 😉 .

**Comment by JFoxUK** [comment]
Ooo Shaun.. don't tempt me ;)

**Comment by shawnchin** [comment]
Closing this PR, but hoping to see this feature in your _proper_ Salesforce Component for Qwil 😉 

Give me a shout if that happens, and I'll be glad to point others to your project and assist where I can.

**Pull request closed without merging**
